language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "rodrigogrohl-github"
    branches:
      - master
      - develop
      - feature/heroku-deploy
script:
- mvn clean install sonar:sonar
deploy:
  provider: heroku
  api_key:
    secure: 57b161ac-4412-4e04-8979-d3d239d540f3
